version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: tiancai
      POSTGRES_PASSWORD: zheng88
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./alembic:/app/alembic
      - ./scripts:/app/scripts
    env_file:
      - .env.production
    environment:
      - ENVIRONMENT=production
    depends_on:
      - redis
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.prod
    volumes:
      - frontend_dist:/usr/share/nginx/html
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api/v1
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl:ro
      - frontend_dist:/usr/share/nginx/html
      - ./uploads:/usr/share/nginx/uploads
    depends_on:
      - frontend
      - backend

volumes:
  redis_data:
  pg_data:
  frontend_dist: