name: myblog
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - aiofiles==24.1.0
      - aiohttp==3.9.1
      - aiosignal==1.3.2
      - aiosmtplib==4.0.1
      - aiosqlite==0.21.0
      - alembic==1.12.1
      - amqp==5.3.1
      - annotated-types==0.7.0
      - anyio==3.7.1
      - APScheduler==3.11.0
      - async-timeout==4.0.3
      - asyncpg==0.30.0
      - attrs==25.3.0
      - Authlib==1.6.0
      - babel==2.17.0
      - bcrypt==4.3.0
      - billiard==4.2.1
      - build==1.2.2.post1
      - CacheControl==0.14.3
      - celery==5.5.3
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - cleo==2.1.0
      - click==8.2.1
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - colorama==0.4.6
      - crashtest==0.4.1
      - cryptography==45.0.4
      - distlib==0.4.0
      - dnspython==2.7.0
      - dulwich==0.22.8
      - ecdsa==0.19.1
      - email_validator==2.2.0
      - exceptiongroup==1.3.0
      - fastapi==0.104.1
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - findpython==0.6.3
      - frozenlist==1.7.0
      - greenlet==3.2.3
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - idna==3.10
      - installer==0.7.0
      - iso8601==2.1.0
      - itsdangerous==2.2.0
      - jaraco.classes==3.4.0
      - jaraco.context==6.0.1
      - jaraco.functools==4.2.1
      - jeepney==0.9.0
      - Jinja2==3.1.6
      - keyring==25.6.0
      - kombu==5.5.4
      - Mako==1.3.10
      - MarkupSafe==3.0.2
      - more-itertools==10.7.0
      - msgpack==1.1.1
      - multidict==6.5.1
      - mypy==1.17.1
      - mypy_extensions==1.1.0
      - packaging==25.0
      - passlib==1.7.4
      - pathspec==0.12.1
      - pbs-installer==2025.7.23
      - pendulum==3.1.0
      - pkginfo==1.12.1.2
      - platformdirs==4.3.8
      - poetry==2.1.3
      - poetry-core==2.1.3
      - prompt_toolkit==3.0.51
      - propcache==0.3.2
      - psycopg2-binary==2.9.10
      - pyasn1==0.6.1
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pycryptodomex==3.23.0
      - pydantic==2.11.7
      - pydantic-settings==2.10.1
      - pydantic_core==2.33.2
      - pyOpenSSL==25.1.0
      - pypika-tortoise==0.6.1
      - pyproject_hooks==1.2.0
      - python-alipay-sdk==3.3.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.0
      - python-jose==3.3.0
      - python-multipart==0.0.6
      - pytz==2025.2
      - PyYAML==6.0.2
      - RapidFuzz==3.13.0
      - redis==6.2.0
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - SecretStorage==3.3.3
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sqladmin==0.20.1
      - SQLAlchemy==2.0.23
      - sqlmodel==0.0.14
      - starlette==0.27.0
      - tomli==2.2.1
      - tomlkit==0.13.3
      - trove-classifiers==2025.5.9.12
      - typing-inspection==0.4.1
      - typing_extensions==4.14.0
      - tzdata==2025.2
      - tzlocal==5.3.1
      - urllib3==2.5.0
      - uvicorn==0.24.0
      - uvloop==0.21.0
      - vine==5.1.0
      - virtualenv==20.32.0
      - watchfiles==1.1.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - wechatpayv3==1.3.11
      - WTForms==3.1.2
      - yarl==1.20.1
      - zstandard==0.23.0

