"""
add tsv columns

Revision ID: 14f51c10ecf0
Revises: e9bef0241515
Create Date: 2025-07-20 20:27:30.830889

Project   : MyBlog FastAPI System
Author    : Gold Zheng
Alembic   : Auto-generated by Alembic Migration System
"""

from typing import Sequence, Union
from alembic import op
from sqlmodel import Text
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision: str = '14f51c10ecf0'
down_revision: Union[str, None] = 'e9bef0241515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    op.add_column('article', sa.Column('tsv_zh', Text, nullable=True))
    op.add_column('article', sa.Column('tsv_en', Text, nullable=True))

def downgrade():
    op.drop_column('article', 'tsv_zh')
    op.drop_column('article', 'tsv_en')
