"""
add tsv columns

Revision ID: e9bef0241515
Revises: ba82d4a780c1
Create Date: 2025-07-20 20:22:12.118163

Project   : MyBlog FastAPI System
Author    : Gold Zheng
Alembic   : Auto-generated by Alembic Migration System
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision: str = 'e9bef0241515'
down_revision: Union[str, None] = 'ba82d4a780c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """
    Upgrade migrations:
    Write your upgrade logic here.
    For example:
        op.create_table(...)
        op.add_column(...)
        op.create_index(...)
    """
    pass


def downgrade() -> None:
    """
    Downgrade migrations:
    Write your downgrade logic here.
    This is the reverse of upgrade().
    """
    pass
